FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install --silent
COPY . .
ENV REACT_APP_API_URL=https://raees1989.pythonanywhere.com
RUN npm run build

FROM node:20-alpine
RUN npm install -g serve
WORKDIR /app
COPY --from=build /app/build ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
